include("${QGC_SOURCE_DIR}/cmake/HybridMavlinkContract.cmake")

set(QGC_MAVLINK_GIT_REPO "https://github.com/QQgdiw/mavlink.git")
set(QGC_MAVLINK_GIT_TAG "qgc-hybrid-change1-v1.16.1-r2")
set(QGC_MAVLINK_DIALECT "qgc_hybrid")
set(QGC_MAVLINK_VERSION "2.0")
set(QGC_DISABLE_APM_MAVLINK OFF)
set(QGC_DISABLE_APM_PLUGIN OFF)

if(CASE STREQUAL "bad_repository")
    set(QGC_MAVLINK_GIT_REPO "https://github.com/mavlink/mavlink.git")
elseif(CASE STREQUAL "bad_tag")
    set(QGC_MAVLINK_GIT_TAG "qgc-hybrid-change1-v1.16.1-r1")
elseif(CASE STREQUAL "bad_dialect")
    set(QGC_MAVLINK_DIALECT "hybrid_vehicle")
elseif(CASE STREQUAL "bad_version")
    set(QGC_MAVLINK_VERSION "1.0")
elseif(CASE STREQUAL "apm_dialect_disabled")
    set(QGC_DISABLE_APM_MAVLINK ON)
elseif(CASE STREQUAL "apm_plugin_disabled")
    set(QGC_DISABLE_APM_PLUGIN ON)
endif()

qgc_validate_hybrid_mavlink_inputs()
